### PR TITLE
(SIMP-2444) Updated pki scheme

### PR DESCRIPTION
**Pull request by nick-markowski**
- New pki scheme
- Real integers and simplib types implemented

SIMP-2444 #close

### CODE REVIEW

**Comment by nick-markowski** [comment]
Don't merge

**Comment by jeefberkey** [comment]
```
  1) An FTP-over-TLS session connection should successfully download a file using FTP-over-SSL
     Failure/Error: on( server, 'setsebool -P ftp_home_dir=1' )
     Beaker::Host::CommandFailure:
       Host 'server' exited with 255 running:
        setsebool -P ftp_home_dir=1
       Last 10 lines of output were:
       	Boolean ftp_home_dir is not defined
       
     # ./spec/acceptance/ftp_tls_connection_spec.rb:143:in `block (3 levels) in <top (required)>'
```

**Comment by nick-markowski** [comment]
@jeefberkey I'm not having that issue

**Comment by jeefberkey** [comment]
@nick-markowski are there fixtures that weren't checked in? If I can't replicate it, it's not working.

**Pull request merged**
