### PR TITLE
(SIMP-4009) Add support for Puppet 5 and OEL

### PR DESCRIPTION
**Pull request by jeefberkey**
- Add support for Puppet 5
- Add reference.md
- Move user/group management to it's own manifest, allowing for easier
  ordering
- Modernized beaker nodesets
- Removed params.pp, it wasn't doing anything productive

SIMP-4009 #comment update vsftpd

### CODE REVIEW

**Comment by jeefberkey** [comment]
https://gitlab.com/simp/pupmod-simp-vsftpd/pipelines/30155319

**Comment by jeefberkey** [comment]
I need to remember what packages to upgrade to fix those ssl issues...

**Comment by ayohrling** [comment]
So the default acceptance tests were only passing because the EL6 hosts were actually using the EL7 boxes; I've been going through this and even the CentOS 6 tests fail. It seems there is a bug with curl 7.19.X that is just dropping the connection. Logging shows TLS connection negotiates, login to FTPd is accepted, but curl drops the connection. I may skip these tests for EL6 for now, and mark a TODO to switch to a different ftp client for testing.

**Comment by jeefberkey** [comment]
@ayohrling that is consistent with what I was seeing on OEL but I chalked it up to OEL being weird or me losing my mind.

**Comment by ayohrling** [comment]
https://gitlab.com/simp/pupmod-simp-vsftpd/pipelines/30556652

**Pull request merged**
